#!/usr/bin/env node
// Copies Leaflet's JavaScript and CSS into packages/shared/src/map/leafletAssets.ts as strings, so every map page
// (websites, Android and iOS WebViews, admin) carries Leaflet itself and never depends on a CDN.
// Run after upgrading the leaflet package: pnpm map:assets
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const require = createRequire(join(ROOT, 'packages', 'shared', 'package.json'));
const dist = dirname(require.resolve('leaflet/dist/leaflet.js'));
const { version } = JSON.parse(readFileSync(join(dist, '..', 'package.json'), 'utf8'));

const js = readFileSync(join(dist, 'leaflet.js'), 'utf8').replace(/\n\/\/# sourceMappingURL=.*$/m, '').trim();
const css = readFileSync(join(dist, 'leaflet.css'), 'utf8').trim();
// The strings are placed inside <script> and <style> tags, so they must not close those tags early.
if (/<\/script/i.test(js) || /<\/style/i.test(css)) throw new Error('Leaflet assets contain a closing tag');

const out = join(ROOT, 'packages', 'shared', 'src', 'map', 'leafletAssets.ts');
writeFileSync(
  out,
  `// Generated by scripts/maps/leaflet-assets.mjs from leaflet@${version}. Don't edit; run pnpm map:assets.
// Leaflet, (c) Volodymyr Agafonkin and contributors, BSD-2-Clause licence: https://github.com/Leaflet/Leaflet/blob/main/LICENSE
/* eslint-disable */
export const LEAFLET_VERSION = ${JSON.stringify(version)};
export const LEAFLET_JS = ${JSON.stringify(js)};
export const LEAFLET_CSS = ${JSON.stringify(css)};
`,
);
console.log(`Wrote ${out} (leaflet ${version}, ${Math.round((js.length + css.length) / 1024)} KB)`);
