// Generated by scripts/brand/render.mjs from brand/mark.svg. Don't edit; change mark.svg and run pnpm brand:assets.
export const BRAND_MARK = {
  viewBox: '0 0 1024 1024',
  handle: 'M 420 384 L 420 332 A 92 92 0 0 1 604 332 L 604 384',
  handleWidth: 46,
  bag: 'M 348 372 L 676 372 Q 724 372 729 420 L 772 764 Q 778 812 730 812 L 294 812 Q 246 812 252 764 L 295 420 Q 300 372 348 372 Z',
  bolt: 'M 548 448 L 440 612 L 506 612 L 474 742 L 588 566 L 520 566 Z',
} as const;
